# Generated by Django 2.0.7 on 2019-09-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='icon',
        ),
    ]
